### PR TITLE
Print AUR packages' popularity

### PR DESCRIPTION
**Pull request by f2404**
Implements #73

### CODE REVIEW

**Comment by larchunix** [comment]
The popularity is rounded down (i.e: 38,00 instead of 38,65 for yaourt package). Is this wanted ?

**Comment by f2404** [comment]
No, this is not intended; and it's working properly for me:
```
$ ./src/package-query -As yaourt
aur/aurtab 1-2 (10) (2.24)
    AUR tab completion for yaourt and apacman using zsh.
aur/lightspark-local 20120810-1 (0) (0.00)
    My modified version of the lightspark-git PKGBUILD; Enhancements: choose between devel and normal buildtype, save changes local even if you use yaourt
aur/pac_manage 1.4-1 (0) (0.00)
    pacman/yaourt helper - manage packages in a single file
aur/pacmanxg 4.16.3-3 (Out of Date) (7) (2.11)
    Yet another GUI for pacman and yaourt. Depends on neither GTK or Qt: only X11
aur/pacmind 2.5-4 (53) (1.95)
    A gtkdialog frontend gui for the package manager, inspired to yaourt-gui
aur/yaourt 1.7-1 (2780) (38.19)
    A pacman wrapper with extended features and AUR support
aur/yaourt-git 1.6-1 [installed: 1.7.72.gdfabddd-1] (Out of Date) (172) (1.70)
    A pacman wrapper with extended features and AUR support
aur/yaourt-gui 1.4-2 (193) (4.33)
    A bash GUI for yaourt
aur/yaourt-gui-manjaro 1.4.5-2 (15) (0.94)
    A bash GUI for yaourt (Manjaro theming) and Romanian translation added
```

**Comment by f2404** [comment]
Does the formatted output (e.g. ```$ ./src/package-query -Aif "%n %p" yaourt```) have the same issue for you?
For me it's fine as well: ```yaourt 38.19```

**Comment by larchunix** [comment]
It's strange:

    $ package-query -As yaourt
    aur/aurtab 1-2 (10) (2,00)
        AUR tab completion for yaourt and apacman using zsh.
    aur/lightspark-local 20120810-1 (0) (0,00)
        My modified version of the lightspark-git PKGBUILD; Enhancements: choose between devel and normal buildtype, save changes local even if you use yaourt
    aur/pac_manage 1.4-1 (0) (0,00)
        pacman/yaourt helper - manage packages in a single file
    aur/pacmanxg 4.16.3-3 (Out of Date) (7) (2,00)
        Yet another GUI for pacman and yaourt. Depends on neither GTK or Qt: only X11
    aur/pacmind 2.5-4 (53) (1,00)
        A gtkdialog frontend gui for the package manager, inspired to yaourt-gui
    aur/yaourt 1.7-1 [installed: 1.7.r76.9ee84f0-1] (2780) (38,00)
        A pacman wrapper with extended features and AUR support
    aur/yaourt-git 1.6-1 (Out of Date) (172) (1,00)
        A pacman wrapper with extended features and AUR support
    aur/yaourt-gui 1.4-2 (194) (4,00)
        A bash GUI for yaourt
    aur/yaourt-gui-manjaro 1.4.5-2 (15) (0,00)
        A bash GUI for yaourt (Manjaro theming) and Romanian translation added

However `%p` is correct:

    $ package-query -Aif "%n %p" yaourt
    yaourt 38.19

**Comment by larchunix** [comment]
Hum, even more strange. Running with `gdb`:

    $ package-query -Ai yaourt
    => Breakpoint 3, json_double (ctx=0x7fffffffe8a0, val=38) at aur.c:496

    $ package-query -Aif "%n %p" yaourt
    => Breakpoint 3, json_double (ctx=0x7fffffffe890, val=38,128202000000002) at aur.c:496

**Comment by f2404** [comment]
Yep, figured out the same here.
It's working fine on my 64-bit installation (the fraction part is there) but does get an integer on a 32-bit installation.
Might be an issue in ```yajl```, I'm thinking.

**Comment by larchunix** [comment]
I ran `gdb` on a 64-bit installation so I don't think this bug is related to the architecture.

**Comment by f2404** [comment]
Yes, I noticed that from the variables addresses length.
Still - I did a clean build on my 64-bit system, and it's working here...

**Comment by f2404** [comment]
Got it! The issue is within ```yajl```, indeed: https://github.com/lloyd/yajl/issues/79
My 'good' installation uses en_US as locale, and the 'bad' one uses ru_RU. Running with C locale fixes the issue:
```
$ LC_ALL=C ./src/package-query -As yaourt
aur/aurtab 1-2 (10) (2.23)
    AUR tab completion for yaourt and apacman using zsh.
aur/lightspark-local 20120810-1 (0) (0.00)
    My modified version of the lightspark-git PKGBUILD; Enhancements: choose between devel and normal buildtype, save changes local even if you use yaourt
aur/pac_manage 1.4-1 (0) (0.00)
    pacman/yaourt helper - manage packages in a single file
aur/pacmanxg 4.16.3-3 (Out of Date) (7) (2.11)
    Yet another GUI for pacman and yaourt. Depends on neither GTK or Qt: only X11
aur/pacmind 2.5-4 (53) (1.95)
    A gtkdialog frontend gui for the package manager, inspired to yaourt-gui
aur/yaourt 1.7-1 (2780) (38.13)
    A pacman wrapper with extended features and AUR support
aur/yaourt-git 1.6-1 [installed: 1.7.69.gfe6a021-1] (Out of Date) (172) (1.70)
    A pacman wrapper with extended features and AUR support
aur/yaourt-gui 1.4-2 (194) (5.32)
    A bash GUI for yaourt
aur/yaourt-gui-manjaro 1.4.5-2 (15) (0.94)
    A bash GUI for yaourt (Manjaro theming) and Romanian translation added
```

**Comment by larchunix** [comment]
This workaround works for me too, still I'm not sure to understand why the result is different between `package-query -Ai yaourt` and `package-query -Aif "%n %p" yaourt` as the code path is mostly the same.

Anyway, let's merge it.

**Comment by f2404** [comment]
I've attempted to workaround the issue - please check the hack I've just pushed.

**Comment by larchunix** [comment]
Works fine with your workaround.

**Pull request merged**
