### PR TITLE
aur.c: current_key as int

### PR DESCRIPTION
**Pull request by f2404**
Convert the current_key field into int.
This will allow to save resources by comparing ints instead of comparing strings.

### CODE REVIEW

**Comment by Skunnyk** [comment]
Can you please rebase your work on master ? :]

**Comment by f2404** [comment]
I think I've accomplished it... wasn't easy for the first time :)

**Comment by Skunnyk** [comment]
Thank you !

**Comment by Skunnyk** [comment]
Woops, seems like this commit break (at least) %G !

```
$ ./src/package-query --aur-url https://aur.archlinux.org -b /var/lib/pacman -c /etc/pacman.conf -SsA yaourt-git -f "%G"       
[1]    7450 segmentation fault (core dumped)  package-query --aur-url https://aur.archlinux.org -b /var/lib/pacman -c  -SsA
```

**Comment by f2404** [comment]
Thanks, I will look into this.

**Comment by f2404** [comment]
Fixed in #41

**Pull request merged**
