### PR TITLE
Fix possible null pointer dereferences

### PR DESCRIPTION
**Pull request by f2404**
plus some code clean-ups

### CODE REVIEW

**Comment by Skunnyk** [comment]
Nice, just need to review it and I'll merge it !

Thank you,

**Comment by f2404** [comment]
Great!
I can continue working on such kind of improvements if you're fine with accepting them. I think many places can be improved.

**Comment by Skunnyk** [comment]
Yes, I think you can continue to improve the code, there is lot of works and package-query needs love :)
I'll release a package-query/yaourt version soon with latest small bugfixes/improvements, then I'll merge all your improvements/reworks !

**Comment by f2404** [comment]
Ok, sounds good. I think I've got some spare love for package-query :)

**Comment by Skunnyk** [comment]
Now that package-query 1.7 is released (https://github.com/archlinuxfr/package-query/releases/tag/1.7), we can work on all this cleaning/improvement stuff :)
Just a side node, can you please be more verbose on your commits messages/descriptions ? That would be perfect :)

**Comment by f2404** [comment]
Ok... do you want me to comment on the already submitted pull requests, or be more verbose in future?

**Comment by Skunnyk** [comment]
Only for future one :)

**Pull request merged**
