### PR TITLE
Issue 10 fix

### PR DESCRIPTION
**Pull request by f2404**
Fixes issue #10

### CODE REVIEW

**Comment by Mikaela** [comment]
You might be interested in https://help.github.com/articles/closing-issues-via-commit-messages/ so when this gets merged it will also close the issue.

**Comment by Mikaela** [comment]
Or more easily https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by f2404** [comment]
Mikaela, thanks!

**Comment by Skunnyk** [comment]
Oh, good catch !
Sounds good, -Qm works, -Qu and -QAu too.

**Pull request merged**
