### PR TITLE
Add ability to sort search results by popularity

### PR DESCRIPTION
**Pull request by f2404**
For #73

### CODE REVIEW

**Comment by larchunix** [comment]
Works for me.

Side note: It would be convenient to add a `--reverse` option for #74 and archlinuxfr/yaourt#210 which are still pending.

**Comment by f2404** [comment]
We do have this option - it's ```--rsort```.

**Comment by larchunix** [comment]
I wasn't aware of it. It deserves to be added to the man page.

**Comment by f2404** [comment]
You are right, it does.
It's mentioned in the help message, though; but maybe I should improve that description, too.

**Pull request merged**
